stages:
  - build
  - deploy

variables:
  build_path: "$project/src/$project"

before_script:
  - "cd $build_path"
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "$project/src/$project"
  script:
    - "cd $build_path"
    - "dotnet build"