stages:
  - build
  - deploy

variables:
  build_path: "$CI_PROJECT_DIR/src/"

before_script:
  - cd $build_path
  - dotnet restore
  - c:\tools\gitversion\gitversion /output buildserver

build:
  stage: build
  script:
    - cd $build_path
    - powershell -File $CI_PROJECT_DIR\build.ps1 Compile --Configuation Release

deploy:
  stage: deploy
  script:
    - cd $build_path
    - powershell -File $CI_PROJECT_DIR\build.ps1 Pack --Configuation Release
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/52/packages/nuget/index.json" --name GitLab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "output/packages/*.nupkg" --source gitlab
  only:
    - master
