stages:
  - build
  - deploy

variables:
  build_path: "$CI_PROJECT_DIR/src/"

before_script:
  - "cd $build_path"
  - "dotnet restore"

build:
  stage: build
  script:
    - "cd $build_path"
    - "dotnet build --no-restore"

pack:
  stage: pack
  script:
    - "cd $build_path"
    - "dotnet pack"
